apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBcC06hpMRLmknTR1GWZZzgnk7xkOGxRcjAePR7gfI76GGS02KbIBVAtjegCtRPHGiYwyKMSNnxBxPYRCSdlJ/CqWoRAgWzABEkN8lf6vHb6UHFFXUzYRjPqgsbYCRZg9JfISKhWMKI4R4BJq9bI/NJ+myULbHTMBPQMPnmlXFy6kqUhF1VMUiQEtDiXCRrfHdDZ7u8l7Uwv4YQnPazMrvM3W2tYphw5TMJUTtlfjrsF30olX0+Sa15KGm70im7YTHb9pMejrne0scrb3mqez+t9pZcLYn6qKuFSmLE3WnS60s3malLwwAt7YhE7fn5VajTI9ygGG7fVzOCDSV6ffxGvRoThWP1OgLQGVExbxm7T9ckC/anFF9ntixddjLi4yj7RR03q/m64pvwtbqbYW6sPheMw3E+hil4RyB+b/zbC+tjpjaQ3hEHhtW8bwMvC3UL5ct9jxAIznLy7eotp1g0pl9NiuwRBdyYsPTh/RD1In1uByH2DCjx5uL599fqUqb3ygZLaCO/g8njPD6MlpCe8luye1qwWxwVIvEeYgCZqjZSwJFshurf4OpceuvHZ5GFUQ7vx+cVPWEkI82czMV70cREfZsfbfcEKRaWb4g27SkhKkhDpefEhqZwLbuj38v6es2MIaEq/L6fy0QQRR5tBN5qRxt7c0Pwzqjt45mW+QdSKAecyYRyNEkwVuYcLcIoj0mnIFe75zWlvr/0Ht6LX2Bvuus32G6G+ehQIz/aQ7GbRYDZ90Kb3ckztC7BBJEFT32e7TAv/pR20DLQU7ULLtMptmFoyNs+BcHzJgWgUtIH6MxNw580fvW+SutS0sWnDMuITX+2bELxKMkupHKP/L/Z4A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

