apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB+eSOMDrXEaLBrExXb9brSz1htOBgyYOY9GXxuAIvMg4Ele1sY2apAFXiLkmkHOc05D/fLQz9nP+foL2Fjxzn4pI+7i1M6ccTD+IewPlWfnM8czrDB2CCsO3A9URKUm2JV+HBTLvSEqkK43+VU3QIizqnObl8mVYM//mLM3hzVfo+Y6xByntCc1Y8KMcaqafMAAM4SzUPv6gRisqheBgXE7NWcuZErmVx94OQxXBat3vy8f2ULlUv1lMpTtyskRFDW5s6X/YROf42ug/qFb3UTlwayWTvEowe6nLpgNiA94tqZoEveL34GjGlJ6zW7Joa5AgUQwwkcCaWr3Qx3cVwKCcKEWoxIEnTpIw8a/zeVKvMi9kzOsRMCwCdto7rDjy/xNp7Q6hiA843kDW0zwsAg2sx9M8dmvzRPyhPgG4n3FWkdjBDWFc13HtmyaGPrqCmRjKCNkvRlMx++df9OI7ggrP3u0UgfXRMXO/135q3yOUmwHkHsxoOIwJsGdxMSyLmBlVOUSQUfvxz7+UyeNDi1CSArJsNQ5AXpCj0J71+/ZVn6qXV8/oOLaj2ZpmugeOou2ByAwg/DO+TzdpXqiqs7FIt0nCYo4UwWOSawtJHGwGO9OX3vJFLILsVOVw7wXQoE6hpJVdrACts8lXyhOpfETxFvEuAb4bqqFmqN1M8LH75/MYSZQO7q4W+wHVbyhYo1gtQ3wfW4WfeQiYdLEVg1s1nDTbZPfM5j5FpAttMAR+c3zonu1bg56V8o6guRC6WXwIig31P10uzydu2tZq+q07UqSLRi70SPx4fU91Upub9SSfB4H3nktuSBt3c9QVQjtgfcXB+vgqQVJjfLh5FDkx7vDoM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

